config/routes.rb
Wote::Application.routes.draw do
  root 'notes#index'

  devise_for :users, only: [:registration, :sign_in, :sign_out, :session]

  resources :notes

end

app/models/note.rb
class Note < ActiveRecord::Base
  validates :title, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.where(user_id: current_user.id)
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render action: 'show', status: :created, location: @note }
      else
        format.html { render action: 'new' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.where(id: params[:id], user_id: current_user.id).limit(1).first
      redirect_to root_path if @note.blank?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :desc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Wote"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-fixed-top.navbar-inverse
      .container
        %a.navbar-brand(href="#{root_path}") Wote
        %ul.nav.navbar-nav.pull-right
          - if current_user
            %li
              = link_to('Sign out', destroy_user_session_path, :method => 'delete')

    .container
      .row
        -# = bootstrap_flash
        = yield
      %footer
        %p &copy; Wote 2014

app/views/notes/_form.html.haml
= form_for @note, :html => { :class => 'form-horizontal' } do |f|
  - if @note.errors.any?
    .alert.alert-danger.alert-dismissable
      %button.close{:type => 'button', :'data-dissmiss' => 'alert', :'aria-hidden' => 'true'} &times;
      %ul
        - @note.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :title, :class => 'control-label'
    = f.text_field :title, :class => 'text_field form-control'
  .form-group
    = f.label :desc, :class => 'control-label'
    = f.text_area :desc, :class => 'text_area form-control', :rows => 20
  .form-group
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), notes_path, :class => 'btn btn-default'

app/views/notes/edit.html.haml
- model_class = Note
= render :partial => "form"

app/views/notes/index.html.haml
- model_class = Note
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:desc)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @notes.each do |note|
      %tr
        %td= link_to note.title.present? ? note.title.scan(/.{1,20}/).first : '', note_path(note)
        %td= note.desc.present? ? note.desc.scan(/.{1,20}/).first : ''
        %td=l note.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_note_path(note), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), note_path(note), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_note_path, :class => 'btn btn-primary'

app/views/notes/new.html.haml
- model_class = Note
= render :partial => "form"

app/views/notes/show.html.haml
- model_class = Note

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @note.title
%p
  %strong= model_class.human_attribute_name(:desc) + ':'
  %br
  = @note.desc


= link_to t('.back', :default => t("helpers.links.back")), notes_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_note_path(@note), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), note_path(@note), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'